// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sis_Escolar.Models;

#nullable disable

namespace Sis_Escolar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240908033131_GradoMigrate")]
    partial class GradoMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sis_Escolar.Models.Calificacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Asignatura")
                        .HasColumnType("longtext");

                    b.Property<string>("Estudiante")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha_Not")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Nota")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Calificacion");
                });

            modelBuilder.Entity("Sis_Escolar.Models.Estudiante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext");

                    b.Property<string>("Dirección")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha_Nacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Grado")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Tutor")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Sis_Escolar.Models.Grado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Grado")
                        .HasColumnType("longtext");

                    b.Property<string>("Profesor_Guia")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("Sis_Escolar.Models.Tutor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Relación")
                        .HasColumnType("longtext");

                    b.Property<string>("Teléfono")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Tutores");
                });
#pragma warning restore 612, 618
        }
    }
}
